//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotFPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginRegex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginRegex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotFPlugins.Properties.PluginRegex", typeof(PluginRegex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateTimeOfLogLine.
        /// </summary>
        internal static string dateTimeOfLogLine {
            get {
                return ResourceManager.GetString("dateTimeOfLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbg.txt.
        /// </summary>
        internal static string DbgFileName {
            get {
                return ResourceManager.GetString("DbgFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\d{5}):Received (?&lt;eqMessage&gt;.+), Player = (?&lt;playerName&gt;.+), zone = (?&lt;zoneName&gt;.+).
        /// </summary>
        internal static string DbgLogPlayerZoneInfo {
            get {
                return ResourceManager.GetString("DbgLogPlayerZoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss yyyy.
        /// </summary>
        internal static string eqDateTimeStampFormat {
            get {
                return ResourceManager.GetString("eqDateTimeStampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;logLine&gt;.+):Adapter #(?&lt;adapterNum&gt;.+) - (?&lt;adapterName&gt;.+)\s:.
        /// </summary>
        internal static string GPUDetect {
            get {
                return ResourceManager.GetString("GPUDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse over user interface element to get description.
        /// </summary>
        internal static string MouseLeave {
            get {
                return ResourceManager.GetString("MouseLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Exited.
        /// </summary>
        internal static string pluginExited {
            get {
                return ResourceManager.GetString("pluginExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug File Parser.
        /// </summary>
        internal static string pluginName {
            get {
                return ResourceManager.GetString("pluginName", resourceCulture);
            }
        }
    }
}
